- fedora
- opensuse
- ubuntu
For https://github.com/ECP-copa/Cabana/pull/325
> add mpi packages (for Cabana)

- .github/workflows/continuous-integration-workflow.yml
- ubuntu
Related to https://github.com/kokkos/kokkos/pull/3679.
> Use CMake 3.17.1 for ubuntu

- .github/workflows/continuous-integration-workflow.yml
This reverts commit b7ad54f80644791615184ce0ea1748547aa2e6c1.
> Revert "Don't set username/password"

- .github/workflows/continuous-integration-workflow.yml
- ubuntu
I couldn't create a branch in kokkos/ci-containers. Let's see if the CI works this time.
> Install CMake into /usr

- fedora
Install step started failing
https://github.com/kokkos/kokkos/blob/897b79da51c1719b620990de4eabba154094bffe/example/build_cmake_installed/CMakeLists.txt#L7
> Install gfortran in Fedora image

- fedora
- opensuse
So we can test kokkos with llvm compiler stack incl. flang.
> fedora: add flang

- .github/workflows/continuous-integration-workflow.yml
- fedora
> Use F33 for icpc

- .github/workflows/continuous-integration-workflow.yml
@dalg24 one more PAT we can remove
> CI: use github token instead of PAT

- .github/workflows/continuous-integration-workflow.yml
> Workaround secomp issue in docker.

- .github/workflows/continuous-integration-workflow.yml
This reverts commit 0350584b4549b9bbfd1380a2e2a9e1b5565a15d8.
Bug #15 has been fixed in the intel package.
> Revert "Use F33 for icpc"

- .github/workflows/continuous-integration-workflow.yml
Reverts kokkos/ci-containers#20
Leads to an docker error in `actions/cache`.
> Revert "Workaround secomp issue in docker."

- .github/workflows/continuous-integration-workflow.yml
Reverts kokkos/ci-containers#22
Docker issue in kokkos fixed in https://github.com/kokkos/kokkos/pull/4361
> Revert "Revert "Workaround secomp issue in docker.""

- .github/workflows/continuous-integration-workflow.yml
Workaround for #24 
/CC @masterleinad
> Build intel on F34

- fedora
- opensuse
- ubuntu
> ccache cleanup

- .github/workflows/continuous-integration-workflow.yml
Seems like the issues with F38 are gone.
> Use F38 for Intel build

- .github/workflows/continuous-integration-workflow.yml
fixes #40 
Upgrading Intel build broke kokkos CI. Go back to F37.
> Revert "Merge pull request #39 from cz4rs/intel-f38"

- .github/workflows/continuous-integration-workflow.yml
F37 will be EOF mid of December 2023.
> CI: use F38 for intel

- fedora
> fedora: add hpx

- .github/workflows/continuous-integration-workflow.yml
- fedora
Try to test the latest kokkos version before pushing new images.
> Build and test kokkos before pushing an updated container

- fedora
flang-devel package got merged into flang package.
> fedora: drop flang-devel for F40

- .github/workflows/continuous-integration-workflow.yml
Fixes the warnings in https://github.com/kokkos/ci-containers/actions/runs/7933880541?pr=48.
> Update versions of actions

- .github/workflows/continuous-integration-workflow.yml
> CI: drop old Intel build on Fedora

- ubuntu
See https://github.com/kokkos/kokkos/pull/8223/files#r2279797638
> ubuntu: add g++-12
